version: "3.9"

services:
 

  prom-server:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
