apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # The port your container is listening on
  type: LoadBalancer  # Set to LoadBalancer or NodePort for external access
